### PR TITLE
Basic Website Structure

### PR DESCRIPTION
**Pull request by Prakhar0409**
## Purpose
Basic website structure towards #1 

## Approach
Basic website structure

## New Issues/FIXME?
Lots - will create issue requests as needed.

## Learning
The website is from one of webjeda's [project](http://webjeda.com)

### CODE REVIEW

**Comment by Prakhar0409** [comment]
@harshit98 I will create other issues once you have merged this PR

**Comment by harshit98** [comment]
Ok, thanks @Prakhar0409 . I'm looking forward to see more contributions from your side. Please open separate issues as well. I will mark them with the `hacktoberfest` label. Good work!

**Review by harshit98 — APPROVED** [review]

**Comment by Prakhar0409** [comment]
@harshit98: Can you also create a branch or make change master branch to host the website (from settings->github pages->source). I don't see anything at http://jaipuropensource.github.io/ as for now :(

**Comment by Prakhar0409** [comment]
This is what it looks like for now: https://prakhar0409.github.io/jaipuropensource.github.io/

**Comment by harshit98** [comment]
@Prakhar0409 Here is the link where it has been hosted: https://jaipur-open-source-community.github.io/jaipuropensource.github.io/

**Pull request merged**
